import Head from "next/head";
import { Features, Footer, Header, MiddleSection, Waves } from "../components";
import home from "../styles/Home.module.scss";
export default function Home() {
  return (
    <div
      style={{
        width: "100%",
        display: "flex",
        flexDirection: "column",
        height: "100%",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Waves />
      <div
        className="centerColumn"
        style={{
          padding: "2rem",
        }}
      >
        <Header />
        <MiddleSection />
        <Features />
      </div>
      <Footer form={false} />
    </div>
  );
}
