import Head from "next/head";
import details from "../styles/Details.module.scss";
import { ContactsArea, DetailsSection, IconButton, Title } from "../components";
export default function Home(props) {
  return (
    <div className={details.detailsContent}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailsSection
        icon="./hotel.svg"
        text="wowowowowowowo"
        backImg="./hotelaria.jpg"
        title="Sáude"
        items={[
          " apresentar e atualizar conteúdos;",
          " otimizar a comunicação no setor;",
          " responder às demandas da sociedade moderna.",
        ]}
      />
      <Title text="Descobrir mais setores" font="2" />
      <div className={details.detailsArea}>
        <IconButton text="Hotelaria" img="./hotelaria.png" url="/hotelaria" />
        <IconButton
          text="Restauração"
          img="./restauracao.png"
          url="/restauracao"
        />
        <IconButton text="Retalho" img="./retalho.png" url="/retalho" />
      </div>
      <ContactsArea />
    </div>
  );
}
